const locationToZoneMap = {
  "Afghanistan, Kabul": "Zone 4",
  "Aland Islands, Mariehamn": "Zone 2",
  "Albania, Tirane": "Zone 3",
  "Algeria, Algiers": "Zone 3",
  "Andorra, Andorra": "Zone 3",
  "Angola, Luanda": "Zone 3",
  "Anguilla, Anguilla": "Zone 2",
  "Antigua and Barbuda, Antigua": "Zone 2",
  "Argentina, Buenos Aires": "Zone 2",
  "Armenia, Yerevan": "Zone 4",
  "Aruba, Aruba": "Zone 2",
  "Ascension Islands, Georgetown": "Zone 3",
  "Australia, Adelaide": "Zone 5",
  "Australia, Eucla": "Zone 5",
  "Australia, Lord Howe": "Zone 5",
  "Australia, Perth": "Zone 5",
  "Australia, Sydney": "Zone 5",
  "Austria, Vienna": "Zone 3",
  "Azerbaijan, Baku": "Zone 4",
  "Bahamas, Nassau": "Zone 2",
  "Bahrain, Bahrain": "Zone 3",
  "Bangladesh, Dhaka": "Zone 4",
  "Barbados, Barbados": "Zone 2",
  "Belarus, Minsk": "Zone 3",
  "Belgium, Brussels": "Zone 3",
  "Belize, Belize": "Zone 1",
  "Benin, Porto": "Zone 3",
  "Bermuda, Bermuda": "Zone 2",
  "Bhutan, Thimphu": "Zone 4",
  "Bolivia, La Paz": "Zone 2",
  "Bosnia and Herzegovina, Sarajevo": "Zone 3",
  "Botswana, Gaborone": "Zone 3",
  "Brazil, Boa Vista": "Zone 2",
  "Brazil, Noronha": "Zone 2",
  "Brazil, Rio Branco": "Zone 2",
  "Brazil, Sao Paulo": "Zone 2",
  "British Indian Ocean Territory, Chagos": "Zone 4",
  "British Virgin Islands, Tortola": "Zone 2",
  "Brunei Darussalam, Brunei - North Asia East Standard Time": "Zone 5",
  "Bulgaria, Sofia": "Zone 3",
  "Burkina Faso, Ouagadougou": "Zone 3",
  "Burundi, Bujumbura": "Zone 3",
  "Cambodia, Phnom Penh": "Zone 4",
  "Cameroon, Douala": "Zone 3",
  "Canada, Edmonton": "Zone 1",
  "Canada, Halifax": "Zone 2",
  "Canada, Montreal": "Zone 2",
  "Canada, St Johns": "Zone 2",
  "Canada, Vancouver": "Zone 1",
  "Canada, Winnipeg": "Zone 1",
  "Canary Islands, Canary": "Zone 3",
  "Cape Verde, Cape Verde": "Zone 2",
  "Cayman Islands, Cayman": "Zone 1",
  "Central African Republic, Bangui": "Zone 3",
  "Chad, Ndjamena": "Zone 3",
  "Chile, Santiago": "Zone 2",
  "China, Shanghai": "Zone 5",
  "China, Hong Kong SAR": "Zone 5",
  "China, Macau SAR": "Zone 5",
  "Christmas Island, Christmas": "Zone 4",
  "Cocos (Keeling) Islands, Cocos": "Zone 4",
  "Colombia, Bogota": "Zone 1",
  "Comoros, Comoro": "Zone 3",
  "Costa Rica, Costa Rica": "Zone 1",
  "Côte d'Ivoire, Abidjan": "Zone 3",
  "Croatia, Zagreb": "Zone 3",
  "Cuba, Havana": "Zone 2",
  "Cyprus, Nicosia": "Zone 3",
  "Czech Republic, Prague": "Zone 3",
  "Democratic Republic of the Congo, Kinshasa": "Zone 3",
  "Democratic Republic of the Congo, Lubumbashi": "Zone 3",
  "Denmark, Copenhagen": "Zone 3",
  "Djibouti, Djibouti": "Zone 3",
  "Dominica, Dominica": "Zone 2",
  "Dominican Republic, Santo Domingo": "Zone 2",
  "Ecuador, Guayaquil": "Zone 1",
  "Egypt, Cairo": "Zone 3",
  "El Salvador, El Salvador": "Zone 1",
  "Equatorial Guinea, Malabo": "Zone 3",
  "Eritrea, Asmara": "Zone 3",
  "Estonia, Tallinn": "Zone 3",
  "Eswatini, Mbabane": "Zone 3",
  "Ethiopia, Addis Ababa": "Zone 3",
  "Falkland Islands, Stanley": "Zone 2",
  "Faroe Islands, Faroe": "Zone 3",
  "Federated States of Micronesia, Kosrae": "Zone 5",
  "Federated States of Micronesia, Truk": "Zone 5",
  "Fiji, Fiji": "Zone 6",
  "Finland, Helsinki": "Zone 3",
  "France, Paris": "Zone 3",
  "French Guiana, Cayenne": "Zone 2",
  "French Polynesia, Marquesas": "Zone 1",
  "French Southern Territories, Kerguelen": "Zone 4",
  "Gabon, Libreville": "Zone 3",
  "Gambia, Banjul": "Zone 3",
  "Georgia (country), Tbilisi": "Zone 4",
  "Germany, Berlin": "Zone 3",
  "Ghana, Accra": "Zone 3",
  "Gibraltar, Gibraltar": "Zone 3",
  "Greece, Athens": "Zone 3",
  "Greenland, Danmarkshavn": "Zone 3",
  "Greenland, Godthab": "Zone 2",
  "Greenland, Scoresbysund": "Zone 2",
  "Greenland, Thule": "Zone 2",
  "Grenada, Grenada": "Zone 2",
  "Guadeloupe, Guadeloupe": "Zone 2",
  "Guam, Guam": "Zone 5",
  "Guatemala, Guatemala": "Zone 1",
  "Guernsey, Guernsey": "Zone 3",
  "Guinea, Conakry": "Zone 3",
  "Guinea-Bissau, Bissau": "Zone 3",
  "Guyana, Guyana": "Zone 2",
  "Haiti, Port": "Zone 1",
  "Honduras, Tegucigalpa": "Zone 1",
  "Hungary, Budapest": "Zone 3",
  "Iceland, Reykjavik": "Zone 3",
  "India, Kolkata": "Zone 4",
  "Indonesia, Jakarta": "Zone 4",
  "Indonesia, Jayapura": "Zone 5",
  "Indonesia, Makassar": "Zone 5",
  "Iran, Tehran": "Zone 4",
  "Iraq, Baghdad": "Zone 3",
  "Ireland, Dublin": "Zone 3",
  "Isle of Man, Isle of Man": "Zone 3",
  "Israel, Jerusalem": "Zone 3",
  "Italy, Rome": "Zone 3",
  "Jamaica, Jamaica": "Zone 1",
  "Japan, Tokyo": "Zone 5",
  "Jersey, Jersey": "Zone 3",
  "Jordan, Amman": "Zone 3",
  "Kazakhstan, Almaty": "Zone 4",
  "Kazakhstan, Oral": "Zone 4",
  "Kenya, Nairobi": "Zone 3",
  "Kiribati, Enderbury": "Zone 6",
  "Kiribati, Kiritimati": "Zone 6",
  "Kiribati, Tarawa": "Zone 6",
  "Kuwait, Kuwait": "Zone 3",
  "Kyrgyzstan, Bishkek": "Zone 4",
  "Laos, Vientiane": "Zone 4",
  "Latvia, Riga": "Zone 3",
  "Lebanon, Beirut": "Zone 3",
  "Lesotho, Maseru": "Zone 3",
  "Liberia, Monrovia": "Zone 3",
  "Libya, Tripoli": "Zone 3",
  "Liechtenstein, Vaduz": "Zone 3",
  "Lithuania, Vilnius": "Zone 3",
  "Luxembourg, Luxembourg": "Zone 3",
  "Madagascar, Antananarivo": "Zone 3",
  "Malawi, Blantyre": "Zone 3",
  "Malaysia, Kuala Lumpur": "Zone 5",
  "Maldives, Maldives": "Zone 4",
  "Mali, Bamako": "Zone 3",
  "Malta, Malta": "Zone 3",
  "Marshall Islands, Kwajalein": "Zone 6",
  "Martinique, Martinique": "Zone 2",
  "Mauritania, Nouakchott": "Zone 3",
  "Mauritius, Mauritius": "Zone 4",
  "Mayotte, Mayotte": "Zone 3",
  "Mexico, Chihuahua": "Zone 1",
  "Mexico, Mexico City": "Zone 1",
  "Mexico, Tijuana": "Zone 1",
  "Moldova, Chisinau": "Zone 3",
  "Monaco, Monaco": "Zone 3",
  "Mongolia, Ulaanbaatar": "Zone 5",
  "Montenegro, Podgorica": "Zone 3",
  "Montserrat, Montserrat": "Zone 2",
  "Morocco, Casablanca": "Zone 3",
  "Mozambique, Maputo": "Zone 3",
  "Myanmar, Rangoon": "Zone 4",
  "Namibia, Windhoek": "Zone 3",
  "Nauru, Nauru": "Zone 6",
  "Nepal, Katmandu": "Zone 4",
  "Netherlands Antilles, Curacao": "Zone 2",
  "Netherlands, Amsterdam": "Zone 3",
  "New Caledonia, Noumea": "Zone 5",
  "New Zealand, Auckland": "Zone 6",
  "New Zealand, Chatham": "Zone 6",
  "Nicaragua, Managua": "Zone 1",
  "Niger, Niamey": "Zone 3",
  "Nigeria, Lagos": "Zone 3",
  "Norfolk Island, Norfolk": "Zone 6",
  "North Korea, Pyongyang": "Zone 5",
  "Northern Mariana Islands, Saipan": "Zone 5",
  "Norway, Oslo": "Zone 3",
  "Oman, Muscat": "Zone 4",
  "Pakistan, Karachi": "Zone 4",
  "Palau, Palau": "Zone 5",
  "Palestinian territories, Gaza": "Zone 3",
  "Panama, Panama": "Zone 1",
  "Papua New Guinea, Port Moresby": "Zone 5",
  "Paraguay, Asuncion": "Zone 2",
  "Peru, Lima": "Zone 1",
  "Philippines, Manila": "Zone 5",
  "Pitcairn, Pitcairn": "Zone 1",
  "Poland, Warsaw": "Zone 3",
  "Portugal, Lisbon": "Zone 3",
  "Puerto Rico, Puerto Rico": "Zone 2",
  "Qatar, Qatar": "Zone 3",
  "Republic of Macedonia, Skopje": "Zone 3",
  "Republic of the Congo, Brazzaville": "Zone 3",
  "Réunion, Reunion": "Zone 4",
  "Romania, Bucharest": "Zone 3",
  "Russia, Moscow": "Zone 4",
  "Rwanda, Kigali": "Zone 3",
  "Saint Barthelemy, Saint Barthelemy": "Zone 2",
  "Saint Helena, St Helena": "Zone 3",
  "Saint Kitts and Nevis, St Kitts": "Zone 2",
  "Saint Lucia, St Lucia": "Zone 2",
  "Saint Pierre and Miquelon, Miquelon": "Zone 2",
  "Saint Vincent and the Grenadines, St Vincent": "Zone 2",
  "San Marino, San Marino": "Zone 3",
  "Sao Tome and Principe, Sao Tome": "Zone 3",
  "Saudi Arabia, Riyadh": "Zone 3",
  "Senegal, Dakar": "Zone 3",
  "Serbia, Belgrade": "Zone 3",
  "Seychelles, Mahe": "Zone 4",
  "Sierra Leone, Freetown": "Zone 3",
  "Singapore, Singapore": "Zone 5",
  "Slovakia, Bratislava": "Zone 3",
  "Slovenia, Ljubljana": "Zone 3",
  "Solomon Islands, Guadalcanal": "Zone 5",
  "Somalia, Mogadishu": "Zone 3",
  "South Africa, Johannesburg": "Zone 3",
  "South Korea, Seoul": "Zone 5",
  "Spain, Madrid": "Zone 3",
  "Sri Lanka, Colombo": "Zone 4",
  "Sudan, Khartoum": "Zone 3",
  "Suriname, Paramaribo": "Zone 2",
  "Sweden, Stockholm": "Zone 3",
  "Switzerland, Zurich": "Zone 3",
  "Syria, Damascus": "Zone 3",
  "Taiwan, Taipei": "Zone 5",
  "Tajikistan, Dushanbe": "Zone 4",
  "Tanzania, Dar es Salaam": "Zone 3",
  "Thailand, Bangkok": "Zone 4",
  "Timor-Leste, Dili": "Zone 5",
  "Togo, Lome": "Zone 3",
  "Tonga, Tongatapu": "Zone 6",
  "Trinidad and Tobago, Port of Spain": "Zone 2",
  "Tunisia, Tunis": "Zone 3",
  "Turkiye, Istanbul": "Zone 3",
  "Turkmenistan, Ashgabat": "Zone 4",
  "Turks and Caicos Islands, Grand Turk": "Zone 2",
  "Tuvalu, Funafuti": "Zone 6",
  "Uganda, Kampala": "Zone 3",
  "Ukraine, Kiev": "Zone 3",
  "United Arab Emirates, Dubai": "Zone 4",
  "United Kingdom, London": "Zone 3",
  "United States Virgin Islands, St Thomas": "Zone 2",
  "United States, Anchorage": "Zone 1",
  "United States, Chicago": "Zone 1",
  "United States, Denver": "Zone 1",
  "United States, Los Angeles": "Zone 1",
  "United States, New York": "Zone 2",
  "United States, Phoenix": "Zone 1",
  "Uruguay, Montevideo": "Zone 2",
  "Uzbekistan, Samarkand": "Zone 4",
  "Vanuatu, Efate": "Zone 5",
  "Vatican City, Vatican": "Zone 3",
  "Venezuela, Caracas": "Zone 2",
  "Vietnam, Hanoi": "Zone 4",
  "Wallis and Futuna, Wallis": "Zone 6",
  "Yemen, Sanaa": "Zone 3",
  "Zambia, Lusaka": "Zone 3",
  "Zimbabwe, Harare": "Zone 3",
};

export function getZoneFromLocation(country, capital) {
  // Normalize the text to remove special characters and accents
  const normalizeString = (str) =>
    str
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-zA-Z0-9, ]/g, "");

  // Normalize the country and capital before creating the key
  const normalizedCountry = normalizeString(country);
  const normalizedCapital = normalizeString(capital);

  const key = `${normalizedCountry}, ${normalizedCapital}`;

  return locationToZoneMap[key] || "Zone not found";
}
